description: lines
baseurl: /
collections:
  category:
    output: true
defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
exclude:
  - hotdogs/
  - doc/
  - stories/
  - gf/
  - birds/
  - social/